<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="enums\" />
    <Folder Include="models\" />
    <Folder Include="modelViews\" />
    <Folder Include="mvvm\" />
    <Folder Include="src\" />
    <Folder Include="views\" />
  </ItemGroup>

</Project>
